version: "3.7"

services:
  sample:
    container_name: react-dockerize
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/ontradeshow"
      - "/ontradeshow/node_modules"
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production